# Commands and Apps to be executed at launch for Frosty Hyprland
exec-once = killall -9 waybar swaync 2>/dev/null || true
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = systemctl --user restart caelestia-shell.service || ~/.local/bin/caelestia-shell &
exec-once = sleep 1 && ~/.config/hypr/scripts/SetAccent.sh $(cat ~/.local/state/accent.txt 2>/dev/null || echo "blue")
